COMMON_FLAGS="-O2 -march=znver3 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--fuse-ld=mold"

MAKEOPTS="-j8 -l8"
EMERGE_DEFAULT_OPTS="--ask --verbose --tree --jobs=1 --load-average=8"
  
FEATURES="sandbox parallel-fetch protect-owned splitdebug"

USE="pipewire alsa dbus nvidia udev -systemd -gnome -cups -doc -debug -handbook -introspection -man -nls -test -telemetry -xinerama"

CPU_FLAGS_X86=""

VIDEO_CARDS="nvidia"

ACCEPT_LICENSE="*"
